apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  ports:
  - port: 80
    name: http
    targetPort: 9080
  - port: 443
    name: https
    targetPort: 9080
  selector:
    app: reviews
  type: NodePort
