apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productpage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - name: productpage
        image: ACCOUNT.dkr.ecr.ap-south-1.amazonaws.com/productpage:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
