apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ratings
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ratings
        version: v2-mysql
    spec:
      containers:
      - name: ratings
        image: ACCOUNT.dkr.ecr.ap-south-1.amazonaws.com/ratings:v1.0
        imagePullPolicy: Always
        env:
          - name: SERVICE_VERSION
            value: "v2"
          - name: DB_TYPE
            value: "mysql"
          - name: MYSQL_DB_HOST
            value: ratings-mysql
          - name: MYSQL_DB_PORT
            value: "3306"
          - name: MYSQL_DB_USER
            value: root
          - name: MYSQL_DB_PASSWORD
            value: powercloud123
        ports:
        - containerPort: 9080
