apiVersion: v1
kind: Service
metadata:
  name: ratings-mysql
  labels:
    app: ratings-mysql
spec:
  ports:
  - port: 3306
    name: http
    targetPort: 3306
  selector:
    app: ratings-mysql
  type: NodePort
